name: First composite action

runs:
  using: composite

  steps:
    - name: ls 1
      run: |
        ls -l
      shell: bash

    - name: Make dir
      run: |
        mkdir test_dir_composite
        echo "secret=something" > test.env
        cat test.env
      shell: bash
      
    - name: ls 2
      run: | 
        ls -l
      shell: bash