name: First composite action

defaults:
  run:
    shell: bash

runs:
  using: composite 
  steps:
    - name: ls 1
      run: |
        ls -l

    - name: Make dir
      run: |
        mkdir test_dir_composite
        echo "secret=something" > test.env
        cat test.env
      
    - name: ls 2
      run: | 
        ls -l