name: Test allow/disallow KV access
on:
  workflow_dispatch:
    inputs:
      operation:
        default: "allow"
        type: choice
        options:
          - allow
          - disallow
      
      getSecret:
        default: "da"
        type: choice
        options:
          - da
          - ne

env:
  KEYVAULT_NAME: "clustersecrets"
  SECRET_NAME: "testSecret"
  AZURE_CLIENT_ID: "fd12270e-bde4-4e04-ba38-7123f295c33b"
  AZURE_TENANT_ID: "b00367e2-193a-4f48-94de-7245d45c0947"
  AZURE_SUBSCRIPTION_ID: "2bae9ddb-756e-421b-83f0-80795ceb6e59"

permissions:
    id-token: write
    contents: read
    issues: write

jobs:
  allow-disallow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Allow one-time access to Key Vault
        if: inputs.operation == 'allow'
        run: |
          sh ./devops/allow_access_to_KV_for_host.sh ${{ env.KEYVAULT_NAME }} ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Revoke one-time access to Key Vault
        if: inputs.operation == 'disallow'
        run: |
          sh ./devops/disallow_access_to_KV_for_host.sh ${{ env.KEYVAULT_NAME }} ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Get secret
        if: inputs.getSecret == 'da'
        run: |
          az keyvault secret show --name "$SECRET_NAME" --vault-name "$KEYVAULT_NAME"