name: Composite action caller

on: [ workflow_dispatch, push ]

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  test_composite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Test ls 
        run: | 
          ls -l

      - name: Make dir
        run: |
          mkdir test_dir

      - name: Test ls 
        run: | 
          ls -l