name: Test Newman
on:  
  push:
  
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to update schema for"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - dev
          - staging
          - prod
          
      region:
        description: "Region"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - eu
          - korea

jobs:
  create-update-schema:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Check Newman version
        run: |
          newman --version
        
      - name: Test Newman
        run: |
          # result=$(newman run postmanCollections/sample-collection.postman_collection.json)
          # echo $result

          const newman = require('newman'); // require newman in your project
          newman.run({
              collection: require('postmanCollections/sample-collection.postman_collection.json'),
              reporters: 'cli'
          }, function (err) {
            if (err) { throw err; }
              console.log('collection run complete!');
          });

      - name: Continue
        run: |
          echo test print