name: Test Newman
on:  
  push:
  
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to update schema for"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - dev
          - staging
          - prod
          
      region:
        description: "Region"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - eu
          - korea

jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Run Smoke tests
        id: smoke_tests
        run: |
          newman run postmanCollections/sample-collection.postman_collection.json --environment postmanCollections/smoke-tests.postman_environment.json \
          && --env-var test=Google

      - name: test failure
        if: always()
        run: |          
          if [ ${{ steps.smoke_tests.outcome }} == 'failure' ]; then
            echo "Rolling back the deployment as smoke tests didn't pass!"

          elif [ ${{ steps.smoke_tests.outcome }} == 'skipped' ]; then
            echo "Workflow canceled!"
          else
            echo "Smoke tests passed! Proceeding!"
          fi
      
      - name: continue
        run: echo continue test