name: Test Newman
on:  
  push:
  
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to update schema for"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - dev
          - staging
          - prod
          
      region:
        description: "Region"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - eu
          - korea

jobs:
  create-update-schema:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Run Smoke tests
        id: smoke_tests
        run: |
          newman run postmanCollections/sample-collection.postman_collection.json  

      - name: test failure
        if: always()
        run: |
          if [ ${{ steps.smoke_tests.outcome }} == 'failure' ]; then
            echo "Rolling back the deployment as smoke tests didn't pass!"
          else
            echo "All good. proceeding!"
          fi
      
      - name: continue
        run: echo continue test