name: Composite action caller

on: [ workflow_dispatch, push ]

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  test_composite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test ls 
        run: | 
          ls -l

      - name: Call composite
        uses: ./actions/

      - name: Test ls 
        run: | 
          ls -l

      - name: Print file
        run: |          
          cat test.env
        shell: bash