name: Composite action caller

on: [ workflow_dispatch, push ]

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  test_composite:
    runs-on: ubuntu-latest
    steps:
      - name: Test ls 
        run: | 
          cd .

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test ls 
        run: | 
          ls -l

      - name: Call composite
        uses: ./actions/

      - name: Test ls 
        run: | 
          ls -l

      - name: Print file
        run: |          
          cat test.env
        shell: bash

      - name: Load env
        id: loaded-env
        run: |
          while IFS= read -r line || [ -n "$line" ]; do
            echo "${line/=/=}" >> "$GITHUB_OUTPUT"
          done < "test.env"
        shell: bash

      - name: Print value from env
        run: |
          echo ${{ steps.loaded-env.outputs.secret }}