name: Test Newman
on:  
  push:
  
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to update schema for"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - dev
          - staging
          - prod
          
      region:
        description: "Region"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - eu
          - korea

jobs:
  create-update-schema:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postmanCollections/sample-collection.postman_collection.json || true
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Error: Newman run command failed with exit code $exit_code"
            # You can send a notification or take corrective actions here
          fi

      - name: Proceed with subsequent steps        
        run: |
          echo test print

      # - name: Capture exit code
      #   run: echo $?

      # - name: Proceed based on result
      #   run: |
      #     if [ $? -eq 0 ]; then
      #       echo "Postman collection ran successfully"
      #       # Proceed with further actions
      #     else
      #       echo "Error: Postman collection failed"
      #       # Take corrective actions or halt the workflow
      #       exit 1
      #     fi