name: Composite action caller

on: [ workflow_dispatch, push ]

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  test_composite:
    runs-on: ubuntu-latest
    steps:
      - name: Test ls 
        run: | 
          ls -l